---
framework: jest
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./tests/spec/*.js"
postMerge:
  pattern: 
    - "./tests/spec/*.js"
postRun:
     command:
        - node --version
configFile: "jest.config.js"
version: 1.0
